### ISSUE TITLE
Are examples installed, or just built?

### ISSUE THREAD

**Issue by Petross404** [KDAB/KDStateMachineEditor#13]
I think that examples option, isn't making a difference to what is installed in the system. They are built, only to be thrown away later, or am I wrong?

**Comment by krf** [comment]
Right, that's on purpose. Examples are not installed. They're basically not useful in binary form, the interesting part is the source code.

**Comment by Petross404** [comment]
Ok, that's what I wanted to know. Feel free to close this :-)
