### ISSUE TITLE
Compatibility with QtCreator scxml files

### ISSUE THREAD

**Issue by forcaeluz** [KDAB/KDStateMachineEditor#18]
We have been using QtCreator for our scxml, but wanted to try this tool to see if it is easier to work with. However, our current state-charts cannot be opened by the tool, as there are a lot of <qt:editorinfo/> xml elements in the scxml files.

I get the error: Failed loading "<my_statemachine.scxml>" - "Unexpected element found while parsing 'state': editorinfo"

My question is, are there plans to support files which have been edited in QtCreator (and contain the qt:editorinfo elements)?

**Comment by winterz** [comment]
@forcaeluz no, we don't have any plans for this feature.  we can accept your contribution if you want to make a patch.  you'll need to sign our Contributors License Agreement if you'd like to pursue that.
