### ISSUE TITLE
Graphviz crashes when build for Windows 64bit

### ISSUE THREAD

**Issue by vyzaq** [KDAB/KDStateMachineEditor#23]
Environment:
- compiler MSVC v144,14.26 x64
- KDStateMachineEditor master edge
- internal graphviz compilation

I built KDSME with x64 MSVC 2019 Update 6, so KDSME crashes on startup because it uses cgraph library from graphviz isn't really 64bit.
the code below from src\core\layout\graphvizlayout\gvutils.cpp:35 uses 64bit pointer on the string (MainWindows c-tor in stack)
`return agopen(const_cast<char *>(qPrintable(name)), kind, disc);`
The problem that cgraph uses unsigned long type for id inside, which is 32bit on Windows 64bit, at the same time cgraph function agmapnametoid() (and idmap() inside) uses char* and convert it to unsigned long as a result pointer is corrupted.
Later during layout cgraph tries to convert 32bit unsigned long to char * - the result is an access violation.

Latest available Graphviz version 2.44.1 compiled Win64 without any problems and worked well.

Looks like internal graphviz works only for 32 bit Windows, which is very rare now IMHO.

**Comment by winterz** [comment]
right, probably time to modernize the internal graphviz build to point to official graphviz code.

**Comment by krf** [comment]
Let me try to have a look at this. Sorry, missed the initial report.

**Comment by krf** [comment]
Fixed.

You can now use the official Graphviz build. The internal (ExternalProject-based build) uses 2.46.0 from Graphviz' Gitlab repository.
