### ISSUE TITLE
qdatabuffer_p.h not found

### ISSUE THREAD

**Issue by bweir** [KDAB/KDStateMachineEditor#3]
Hi there,

I took a stab at compiling the project but ran into this stumbling block.
```
In file included from /home/brett/KDStateMachineEditor/src/view/quick/qopengl2pexvertexarray.cpp:42:0:
/home/brett/KDStateMachineEditor/src/view/quick/qopengl2pexvertexarray_p.h:58:35: fatal error: private/qdatabuffer_p.h: No such file or directory
 #include <private/qdatabuffer_p.h>
                                   ^
compilation terminated.
src/view/CMakeFiles/kdstatemachineeditor_view.dir/build.make:381: recipe for target 'src/view/CMakeFiles/kdstatemachineeditor_view.dir/quick/qopengl2pexvertexarray.cpp.o' failed
make[2]: *** [src/view/CMakeFiles/kdstatemachineeditor_view.dir/quick/qopengl2pexvertexarray.cpp.o] Error 1
CMakeFiles/Makefile2:2195: recipe for target 'src/view/CMakeFiles/kdstatemachineeditor_view.dir/all' failed
make[1]: *** [src/view/CMakeFiles/kdstatemachineeditor_view.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

Using `find` on the project would indicate that the file doesn't exist. Any ideas?

**Comment by winterz** [comment]
I have that file installed from the Fedora distro package qt5-qtbase-devel

but yes ideally the build system would warn about missing private headers. something to fix before the 1.0 release

**Comment by bweir** [comment]
Ahh, okay then. I am curious. As someone who has only worked with the published API, why does your application need to access Qt's private headers?

Also, I've submitted a pull request with the dependencies I needed to build/run your app (not included by qt5-default).

**Comment by krf** [comment]
This was solved by installing the proper devel packages, right?

Closing then.
