### ISSUE TITLE
Wrong install location of .lib and .cmake files on Windows

### ISSUE THREAD

**Issue by e4z9** [KDAB/KDStateMachineEditor#6]
The `.lib` files are installed to `bin/` which is not what other Qt modules do, and the `.cmake` files are installed to `bin/cmake` which leads to e.g. a GammaRay build not finding the cmake files when installing KDSME into a Qt install and giving cmake `CMAKE_PREFIX_PATH=<QtInstallPath>`

**Comment by krf** [comment]
Fixed by commit 7e87a4662132a284bd4235bc9b4d281a30d6e2cf

**Comment by e4z9** [comment]
thanks
