### ISSUE TITLE
SIGSEGV when running kdstatemachineeditor.exe MinGW/MSVC, windows 7, Qt5.5.1

### ISSUE THREAD

**Issue by LangeSebastian** [KDAB/KDStateMachineEditor#7]
Build sucessfully crash during runtime. GraphViz is omitted.
Manually setting graphviz libs/path results in error in CMakeLists.txt@89 find_package(GraphViz), since it does not include graphviz_version.h (v2.38.0) and incompatible libraries, therefor building without graphviz.

Crash in Release and Debug Mode. In Debug Mode no StackTraceData within QtCreator possible, crash seems to happen outside of some dll.

Depency Walker resolves all but the typical. One issue found is Link Checksum is not the Real Checksum: 0x05A681BC (link) vs 0x05A681E (real). During build/link process the correct files should be used. Tried running from command line as from QtCreator (same problem).

[CMakeCache.txt](https://github.com/KDAB/KDStateMachineEditor/files/92059/CMakeCache.txt)

All test_\* commands run successfully (PASS).
simplestatemachine.exe and kdstatemachineeditor.exe both crash.

If you need any further information (or tests) feel free to contact me.
I will give it another shot with another build setup (windows)

...

> =library-loaded,id="C:\Windows\SysWOW64\ddraw.dll",target-name="C:\Windows\SysWOW64\ddraw.dll",host-name="C:\Windows\SysWOW64\ddraw.dll",symbols-loaded="0",thread-group="i1"
> sBibliothek C:\Windows\SysWOW64\ddraw.dll geladen
> 
> =library-loaded,id="C:\Windows\SysWOW64\dciman32.dll",target-name="C:\Windows\SysWOW64\dciman32.dll",host-name="C:\Windows\SysWOW64\dciman32.dll",symbols-loaded="0",thread-group="i1"
> sBibliothek C:\Windows\SysWOW64\dciman32.dll geladen
> 
> =library-loaded,id="C:\Windows\SysWOW64\ig4icd32.dll",target-name="C:\Windows\SysWOW64\ig4icd32.dll",host-name="C:\Windows\SysWOW64\ig4icd32.dll",symbols-loaded="0",thread-group="i1"
> sBibliothek C:\Windows\SysWOW64\ig4icd32.dll geladen
> 
> ~"\nProgram received signal "
> ~"SIGSEGV, Segmentation fault.\n"
> ~"[Switching to Thread 7136.0x1760]\n"
> ~"0x313e2dc4 in ?? () from C:\Windows\SysWOW64\ig4icd32.dll\n"
> *stopped,reason="signal-received",signal-name="SIGSEGV",signal-meaning="Segmentation fault",frame={addr="0x313e2dc4",func="??",args=[],from="C:\Windows\SysWOW64\ig4icd32.dll"},thread-id="1",stopped-threads="all"
> dNOTE: INFERIOR SPONTANEOUS STOP
> sStopped.
> dState changed from InferiorRunOk(11) to InferiorStopOk(14) [master]
> dHANDLING SIGNAL SIGSEGV
> sStopped: Segmentation fault (Signal SIGSEGV).
> ...
> ~"Dump of assembler code from 0x313e2db0 to 0x313e2e28:\n"
> ~"   0x313e2db0:\t8b 0b\tmov    (%ebx),%ecx\n"
> ~"   0x313e2db2:\t83 f9 ff\tcmp    $0xffffffff,%ecx\n"
> ~"   0x313e2db5:\t74 33\tje     0x313e2dea\n"
> ~"   0x313e2db7:\t8b 86 58 a2 00 00\tmov    0xa258(%esi),%eax\n"
> ~"   0x313e2dbd:\t8b 8c 88 b4 00 00 00\tmov    0xb4(%eax,%ecx,4),%ecx\n"
> ~"=> 0x313e2dc4:\t8b 41 50\tmov    0x50(%ecx),%eax\n"
> ~"   0x313e2dc7:\t83 c0 10\tadd    $0x10,%eax\n"
> ~"   0x313e2dca:\tb9 00 00 00 00\tmov    $0x0,%ecx\n"
> ~"   0x313e2dcf:\t74 0e\tje     0x313e2ddf\n"
> ~"   0x313e2dd1:\t39 30\tcmp    %esi,(%eax)\n"
> ~"   0x313e2dd3:\t75 03\tjne    0x313e2dd8\n"
> ~"   0x313e2dd5:\t8b 48 04\tmov    0x4(%eax),%ecx\n"
> ~"   0x313e2dd8:\t8b 40 08\tmov    0x8(%eax),%eax\n"
> ~"   0x313e2ddb:\t85 c0\ttest   %eax,%eax\n"
> ~"   0x313e2ddd:\t75 f2\tjne    0x313e2dd1\n"
> ~"   0x313e2ddf:\t51\tpush   %ecx\n"
> ~"   0x313e2de0:\t55\tpush   %ebp\n"
> ~"   0x313e2de1:\t32 d2\txor    %dl,%dl\n"
> ~"   0x313e2de3:\t8b ce\tmov    %esi,%ecx\n"
> ~"   0x313e2de5:\te8 56 fb ff ff\tcall   0x313e2940\n"
> ~"   0x313e2dea:\t47\tinc    %edi\n"
> ~"   0x313e2deb:\t83 c3 04\tadd    $0x4,%ebx\n"
> ~"   0x313e2dee:\t3b be d4 0b 00 00\tcmp    0xbd4(%esi),%edi\n"
> ~"   0x313e2df4:\t7c ba\tjl     0x313e2db0\n"
> ~"   0x313e2df6:\t5b\tpop    %ebx\n"
> ~"   0x313e2df7:\t5f\tpop    %edi\n"
> ~"   0x313e2df8:\t5e\tpop    %esi\n"
> ~"   0x313e2df9:\t5d\tpop    %ebp\n"
> ~"   0x313e2dfa:\tc3\tret    \n"
> ~"   0x313e2dfb:\tcc\tint3   \n"
> ~"   0x313e2dfc:\tcc\tint3   \n"
> ~"   0x313e2dfd:\tcc\tint3   \n"
> ~"   0x313e2dfe:\tcc\tint3   \n"
> ~"   0x313e2dff:\tcc\tint3   \n"
> ~"   0x313e2e00:\t8b 42 50\tmov    0x50(%edx),%eax\n"
> ~"   0x313e2e03:\t83 c0 10\tadd    $0x10,%eax\n"
> ~"   0x313e2e06:\t56\tpush   %esi\n"
> ~"   0x313e2e07:\tbe 00 00 00 00\tmov    $0x0,%esi\n"
> ~"   0x313e2e0c:\t74 10\tje     0x313e2e1e\n"
> ~"   0x313e2e0e:\t8b ff\tmov    %edi,%edi\n"
> ~"   0x313e2e10:\t39 08\tcmp    %ecx,(%eax)\n"
> ~"   0x313e2e12:\t75 03\tjne    0x313e2e17\n"
> ~"   0x313e2e14:\t8b 70 04\tmov    0x4(%eax),%esi\n"
> ~"   0x313e2e17:\t8b 40 08\tmov    0x8(%eax),%eax\n"
> ~"   0x313e2e1a:\t85 c0\ttest   %eax,%eax\n"
> ~"   0x313e2e1c:\t75 f2\tjne    0x313e2e10\n"
> ~"   0x313e2e1e:\t8b 44 24 08\tmov    0x8(%esp),%eax\n"
> ~"   0x313e2e22:\t8b 40 50\tmov    0x50(%eax),%eax\n"
> ~"   0x313e2e25:\t83 c0 10\tadd    $0x10,%eax\n"
> ~"End of assembler dump.\n"

**Comment by krf** [comment]
Is this still valid?

**Comment by LangeSebastian** [comment]
Hey there,

we actually did not test it, nor use it currently, therefore I would call it as obsolete
